# Full color support
set -g default-terminal "xterm-256color"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'

# sessionx
set -g @plugin 'omerxx/tmux-sessionx'
# set -g @sessionx-tmuxinator-mode 'on'
set -g @sessionx-tmuxinator-mode 'off'
set -g @sessionx-window-mode 'on'
# set -g @sessionx-x-path '/home/jaryd/.config/tmuxinator'
# set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-zoxide-mode 'off'

# Enable mouse
set -g mouse on
set -ga terminal-overrides ',*256color*:smcup@:rmcup@'

# Resurrect
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'

# vi mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "xclip -selection clipboard -in"

# new-window
bind-key C new-window -c "#{pane_current_path}" -n "#{basename:#{pane_current_path}}"

# got to marked pane
bind \` switch-client -t'{marked}'

# choose buffer to paste interactively (default key was '=')
bind-key p choose-buffer

# SET NEW WINDOW INITIAL PATH BASED FROM CURRENT WINDOW
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Smart pane switching with awareness of Vim splits.
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

# ----------------------
# Status Bar
# -----------------------
set-option -g status on                # turn the status bar on
set -g status-interval 2               # set update frequencey (default 15 seconds)
set -g status-justify centre           # center window list for clarity
set -g status-right ' %a %h-%d %H:%M:%S '

# visual notification of activity in other windows
setw -g monitor-activity on
set -g visual-activity on

# Panes
bind up resize-pane -U 10
bind down resize-pane -D 10
bind left resize-pane -L 30
bind right resize-pane -R 30
#bind tab next-layout
unbind C-o
bind space select-pane -t:.+

# window title
# enable wm window titles
set-option -g set-titles on

# No escape time for vi mode
set -sg escape-time 0

# sync panes
bind C-e command-prompt -p "Command:" \
         "run \"tmux list-panes -s -F '##{session_name}:##{window_index}.##{pane_index}' \
                | xargs -I PANE tmux send-keys -t PANE '%1' Enter\""

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run-shell ~/.tmux/plugins/sidebarplus/sidebar-plus.tmux
run '~/.tmux/plugins/tpm/tpm'
